import { Client, Job, Quote, Invoice, ServiceCatalogItem, CompanySettings } from '@/types';

export const initialCompanySettings: CompanySettings = {
  companyName: 'Jardin du Coin - Services Paysagers',
  slogan: 'Entretien & Aménagement Paysager Rive-Sud',
  phone: '(450) 840-2819',
  email: 'service@jardinducoin.ca',
  address: '345 Boul. Taschereau, Brossard, QC J4W 2H6',
  website: 'www.jardinducoin.ca',
  neq: '1178945623',
  tpsNumber: '839201948 RT0001',
  tvqNumber: '1209384756 TQ0001',
  interacEmail: 'paiement@jardinducoin.ca',
  interacQuestion: 'Nom de votre municipalité',
  interacAnswer: 'Brossard',
  defaultPaymentTermsDays: 14,
  taxRateTPS: 0.05,
  taxRateTVQ: 0.09975,
  defaultLanguage: 'fr',
};

export const serviceCatalog: ServiceCatalogItem[] = [
  {
    id: 'srv-1',
    type: 'lawn_mowing',
    titleFr: 'Tonte de pelouse régulière',
    titleEn: 'Regular Lawn Mowing',
    descriptionFr: 'Tonte propre, découpe des bordures (weed trimming) et soufflage des résidus sur l’entrée et trottoirs.',
    descriptionEn: 'Clean cut mowing, edge trimming, and blowing clippings from driveways/walkways.',
    defaultUnit: 'visite',
    defaultUnitPrice: 45.0,
  },
  {
    id: 'srv-2',
    type: 'hedge_trimming',
    titleFr: 'Taillage de haie de cèdres',
    titleEn: 'Cedar Hedge Trimming',
    descriptionFr: 'Taille précise de niveau, ramassage complet des retailles et transport.',
    descriptionEn: 'Level precise trimming, full rake & cleanup of clippings with disposal.',
    defaultUnit: 'pi linéaire',
    defaultUnitPrice: 4.5,
  },
  {
    id: 'srv-3',
    type: 'spring_cleanup',
    titleFr: 'Grand ménage de printemps',
    titleEn: 'Spring Property Cleanup',
    descriptionFr: 'Déchaumage/râtelage vigoureux de la pelouse, nettoyage des plates-bandes, ramassage des débris d’hiver et gravier.',
    descriptionEn: 'Power raking/dethatching, garden bed clearing, winter debris & gravel removal.',
    defaultUnit: 'forfait',
    defaultUnitPrice: 280.0,
  },
  {
    id: 'srv-4',
    type: 'aeration_seeding',
    titleFr: 'Aération mécanique & Terreautage',
    titleEn: 'Core Aeration & Topdressing',
    descriptionFr: 'Carottage du sol pour décompacter la terre, épandage de compost marin et sursemis de semences robustes.',
    descriptionEn: 'Core aeration for soil decompression, topsoil compost spreading & overseeding.',
    defaultUnit: 'forfait',
    defaultUnitPrice: 195.0,
  },
  {
    id: 'srv-5',
    type: 'mulch_soil',
    titleFr: 'Pose de paillis de cèdre naturel',
    titleEn: 'Cedar Mulch Installation',
    descriptionFr: 'Désherbage préalable, délimitation des bordures et étalage de paillis premium brun ou noir (3 pouces).',
    descriptionEn: 'Pre-weeding, bed edging, and laying 3 inches of premium brown/black cedar mulch.',
    defaultUnit: 'verge cube',
    defaultUnitPrice: 110.0,
  },
  {
    id: 'srv-6',
    type: 'landscaping',
    titleFr: 'Aménagement de plate-bande & Pierres',
    titleEn: 'Garden Bed Design & River Rock',
    descriptionFr: 'Installation de géotextile commercial, galets de rivière et plantation d’arbustes vivaces résistants.',
    descriptionEn: 'Heavy duty weed barrier installation, river rocks and low-maintenance perennials planting.',
    defaultUnit: 'forfait',
    defaultUnitPrice: 850.0,
  },
  {
    id: 'srv-7',
    type: 'fall_cleanup',
    titleFr: 'Nettoyage d’automne & Ramassage de feuilles',
    titleEn: 'Fall Cleanup & Leaf Removal',
    descriptionFr: 'Soufflage et aspiration des feuilles mortes, coupe des vivaces et fermeture du terrain pour l’hiver.',
    descriptionEn: 'Blowing & bagging of leaves, perennial trim, and winter property prep.',
    defaultUnit: 'forfait',
    defaultUnitPrice: 240.0,
  },
];

export const initialClients: Client[] = [
  {
    id: 'cli-101',
    name: 'Marc-André Tremblay',
    companyName: 'Résidence Tremblay',
    phone: '(514) 795-1823',
    email: 'ma.tremblay88@gmail.com',
    address: '428 Rue Saint-Charles Ouest',
    sector: 'Longueuil',
    postalCode: 'J4H 1G3',
    gateCode: 'Clé sur barrière côté garage',
    hasDogs: false,
    lawnSizeSqFt: 4500,
    notes: 'Arroseurs automatiques programmés à 6h00 le matin. Attention aux rosiers près de la terrasse.',
    tags: ['Tonte Hebdo', 'Client Or', 'Contrat Annuel'],
    status: 'active',
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-09-01T14:30:00Z',
  },
  {
    id: 'cli-102',
    name: 'Sophie Lavoie',
    phone: '(450) 678-9921',
    email: 'sophie.lavoie@videotron.ca',
    address: '1540 Rue des Mélèzes',
    sector: 'Saint-Bruno',
    postalCode: 'J3V 4P8',
    gateCode: 'Code: 4829#',
    hasDogs: true,
    dogNotes: 'Golden Retriever nommé Barney (très gentil mais fermer la barrière hermétiquement).',
    lawnSizeSqFt: 7200,
    notes: 'Haie de cèdres de 120 pi linéaires à tailler chaque fin d’été.',
    tags: ['Tonte Hebdo', 'Haie de cèdres', 'Chiens'],
    status: 'active',
    createdAt: '2026-04-15T11:00:00Z',
    updatedAt: '2026-09-05T10:15:00Z',
  },
  {
    id: 'cli-103',
    name: 'David Chen',
    companyName: 'Chen & Associés Inc.',
    phone: '(514) 812-4430',
    email: 'david.chen@gmail.com',
    address: '7825 Boulevard Rome',
    sector: 'Brossard',
    postalCode: 'J4Y 1S2',
    gateCode: 'Entrée libre des deux côtés',
    hasDogs: false,
    lawnSizeSqFt: 3800,
    notes: 'Proche du Quartier DIX30. Préfère les passages le mardi ou mercredi avant-midi.',
    tags: ['Tonte Bi-hebdo', 'Client 2026'],
    status: 'active',
    createdAt: '2026-05-02T08:30:00Z',
    updatedAt: '2026-09-10T16:00:00Z',
  },
  {
    id: 'cli-104',
    name: 'Élise Beauchamp',
    phone: '(450) 449-3310',
    email: 'elise.beauchamp@outlook.com',
    address: '210 Rue De Montbrun',
    sector: 'Boucherville',
    postalCode: 'J4B 4T5',
    gateCode: 'Pas de barrière',
    hasDogs: false,
    lawnSizeSqFt: 5500,
    notes: 'Grande cour avec piscine creusée. Ne pas souffler de débris vers la toile de piscine.',
    tags: ['Piscine', 'Tonte Hebdo', 'Boucherville'],
    status: 'active',
    createdAt: '2026-05-12T13:45:00Z',
    updatedAt: '2026-09-08T09:20:00Z',
  },
  {
    id: 'cli-105',
    name: 'Guillaume & Karine Roy',
    phone: '(514) 991-7782',
    email: 'roy.guillaume@sympatico.ca',
    address: '88 Avenue Elm',
    sector: 'Saint-Lambert',
    postalCode: 'J4P 1W3',
    gateCode: 'Code: 1984',
    hasDogs: true,
    dogNotes: 'Deux petits Carlins à l’intérieur pendant les travaux.',
    lawnSizeSqFt: 3200,
    notes: 'Terrain ombragé avec vieux érables. Beaucoup de ramassage de feuilles à prévoir.',
    tags: ['Saint-Lambert', 'Fermeture Terrain'],
    status: 'active',
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-09-12T11:00:00Z',
  },
  {
    id: 'cli-106',
    name: 'Mathieu Gagnon',
    phone: '(450) 659-4011',
    email: 'm.gagnon.candiac@gmail.com',
    address: '65 Rue Montcalm',
    sector: 'Candiac',
    postalCode: 'J5R 3L7',
    gateCode: 'Loquet manuel haut',
    hasDogs: false,
    lawnSizeSqFt: 6100,
    notes: 'Demande soumission pour ajout de pavé uni et muret autour de l’arbre avant.',
    tags: ['Lead Projet Pavé', 'Candiac'],
    status: 'lead',
    createdAt: '2026-09-02T15:20:00Z',
    updatedAt: '2026-09-02T15:20:00Z',
  },
  {
    id: 'cli-107',
    name: 'Hélène Bouchard',
    phone: '(450) 444-1234',
    email: 'helene.bouchard@hotmail.com',
    address: '320 Rue Saint-Henri',
    sector: 'La Prairie',
    postalCode: 'J5R 2T1',
    gateCode: 'Accès facile',
    hasDogs: false,
    lawnSizeSqFt: 4000,
    notes: 'Vieux La Prairie. Entrée étroite pour la tondeuse 48 po.',
    tags: ['Tonte Bi-hebdo', 'La Prairie'],
    status: 'active',
    createdAt: '2026-05-20T14:00:00Z',
    updatedAt: '2026-09-11T17:10:00Z',
  },
];

export const initialJobs: Job[] = [
  {
    id: 'job-501',
    clientId: 'cli-103',
    clientName: 'David Chen',
    clientPhone: '(514) 812-4430',
    address: '7825 Boulevard Rome',
    sector: 'Brossard',
    serviceType: 'lawn_mowing',
    date: new Date().toISOString().split('T')[0], // Today
    timeSlot: 'morning',
    status: 'pending',
    priority: 'normal',
    recurrence: 'weekly',
    price: 45.0,
    gateCode: 'Entrée libre des deux côtés',
    hasDogs: false,
    notes: 'Vérifier la hauteur de coupe à 3.0 po.',
  },
  {
    id: 'job-502',
    clientId: 'cli-101',
    clientName: 'Marc-André Tremblay',
    clientPhone: '(514) 795-1823',
    address: '428 Rue Saint-Charles Ouest',
    sector: 'Longueuil',
    serviceType: 'lawn_mowing',
    date: new Date().toISOString().split('T')[0], // Today
    timeSlot: 'morning',
    status: 'pending',
    priority: 'normal',
    recurrence: 'weekly',
    price: 48.0,
    gateCode: 'Clé sur barrière côté garage',
    hasDogs: false,
    notes: 'Bien souffler le pourtour de la terrasse en composite.',
  },
  {
    id: 'job-503',
    clientId: 'cli-104',
    clientName: 'Élise Beauchamp',
    clientPhone: '(450) 449-3310',
    address: '210 Rue De Montbrun',
    sector: 'Boucherville',
    serviceType: 'lawn_mowing',
    date: new Date().toISOString().split('T')[0], // Today
    timeSlot: 'afternoon',
    status: 'pending',
    priority: 'normal',
    recurrence: 'weekly',
    price: 55.0,
    gateCode: 'Pas de barrière',
    hasDogs: false,
    notes: 'Attention à la toile de piscine creusée.',
  },
  {
    id: 'job-504',
    clientId: 'cli-102',
    clientName: 'Sophie Lavoie',
    clientPhone: '(450) 678-9921',
    address: '1540 Rue des Mélèzes',
    sector: 'Saint-Bruno',
    serviceType: 'hedge_trimming',
    customServiceName: 'Taillage haie de cèdres (120 pi)',
    date: new Date().toISOString().split('T')[0], // Today
    timeSlot: 'afternoon',
    status: 'pending',
    priority: 'high',
    recurrence: 'one_off',
    price: 540.0,
    gateCode: 'Code: 4829#',
    hasDogs: true,
    notes: 'Chien Barney. Apporter l’échafaudage et les bâches pour les retailles.',
  },
  {
    id: 'job-505',
    clientId: 'cli-105',
    clientName: 'Guillaume & Karine Roy',
    clientPhone: '(514) 991-7782',
    address: '88 Avenue Elm',
    sector: 'Saint-Lambert',
    serviceType: 'aeration_seeding',
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0], // Tomorrow
    timeSlot: 'morning',
    status: 'pending',
    priority: 'normal',
    recurrence: 'one_off',
    price: 195.0,
    gateCode: 'Code: 1984',
    hasDogs: true,
    notes: 'Passer l’aérateur deux fois dans la section nord ombragée.',
  },
  {
    id: 'job-506',
    clientId: 'cli-107',
    clientName: 'Hélène Bouchard',
    clientPhone: '(450) 444-1234',
    address: '320 Rue Saint-Henri',
    sector: 'La Prairie',
    serviceType: 'lawn_mowing',
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0], // Tomorrow
    timeSlot: 'afternoon',
    status: 'pending',
    priority: 'normal',
    recurrence: 'biweekly',
    price: 45.0,
    gateCode: 'Accès facile',
    hasDogs: false,
    notes: 'Passage aux 2 semaines.',
  },
];

export const initialQuotes: Quote[] = [
  {
    id: 'quo-301',
    quoteNumber: 'DEV-2026-089',
    clientId: 'cli-106',
    clientName: 'Mathieu Gagnon',
    clientEmail: 'm.gagnon.candiac@gmail.com',
    clientPhone: '(450) 659-4011',
    address: '65 Rue Montcalm',
    sector: 'Candiac',
    date: '2026-09-04',
    validUntil: '2026-10-04',
    items: [
      {
        id: 'item-1',
        serviceType: 'landscaping',
        description: 'Excavation, pose de géotextile, lit de pose et pavé uni pour entrée secondaire (140 pi²)',
        quantity: 1,
        unit: 'forfait',
        unitPrice: 1850.0,
        total: 1850.0,
      },
      {
        id: 'item-2',
        serviceType: 'mulch_soil',
        description: 'Ajout de terreau enrichi et plantation de 6 arbustes vivaces',
        quantity: 1,
        unit: 'forfait',
        unitPrice: 420.0,
        total: 420.0,
      },
    ],
    subtotal: 2270.0,
    tps: 113.5,
    tvq: 226.43,
    total: 2609.93,
    applyTaxes: true,
    notes: 'Estimation valide pour 30 jours. Dépôt de 30% requis à la confirmation de la date du chantier.',
    status: 'sent',
    createdAt: '2026-09-04T10:30:00Z',
  },
  {
    id: 'quo-302',
    quoteNumber: 'DEV-2026-088',
    clientId: 'cli-102',
    clientName: 'Sophie Lavoie',
    clientEmail: 'sophie.lavoie@videotron.ca',
    clientPhone: '(450) 678-9921',
    address: '1540 Rue des Mélèzes',
    sector: 'Saint-Bruno',
    date: '2026-08-28',
    validUntil: '2026-09-28',
    items: [
      {
        id: 'item-1',
        serviceType: 'hedge_trimming',
        description: 'Taillage de haie de cèdres mature (120 pi linéaires) recto-verso et tête',
        quantity: 120,
        unit: 'pi linéaire',
        unitPrice: 4.5,
        total: 540.0,
      },
    ],
    subtotal: 540.0,
    tps: 27.0,
    tvq: 53.87,
    total: 620.87,
    applyTaxes: true,
    notes: 'Travail approuvé par courriel. Prévu mi-septembre.',
    status: 'accepted',
    createdAt: '2026-08-28T14:15:00Z',
    acceptedAt: '2026-08-30T09:00:00Z',
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-801',
    invoiceNumber: 'FAC-2026-142',
    clientId: 'cli-101',
    clientName: 'Marc-André Tremblay',
    clientEmail: 'ma.tremblay88@gmail.com',
    clientPhone: '(514) 795-1823',
    address: '428 Rue Saint-Charles Ouest',
    sector: 'Longueuil',
    issueDate: '2026-08-31',
    dueDate: '2026-09-14',
    items: [
      {
        id: 'item-1',
        serviceType: 'lawn_mowing',
        description: 'Forfait mensuel de tonte de pelouse - Août 2026 (4 passages)',
        quantity: 4,
        unit: 'visite',
        unitPrice: 48.0,
        total: 192.0,
      },
      {
        id: 'item-2',
        serviceType: 'fertilization',
        description: 'Traitement fertilisant d’été - pelouse saine sans mauvaises herbes',
        quantity: 1,
        unit: 'forfait',
        unitPrice: 85.0,
        total: 85.0,
      },
    ],
    subtotal: 277.0,
    tps: 13.85,
    tvq: 27.63,
    total: 318.48,
    applyTaxes: true,
    status: 'paid',
    paidAmount: 318.48,
    paymentMethod: 'interac',
    paymentDate: '2026-09-03',
    notes: 'Paiement reçu par Virement Interac. Merci pour votre confiance !',
    createdAt: '2026-08-31T17:00:00Z',
  },
  {
    id: 'inv-802',
    invoiceNumber: 'FAC-2026-143',
    clientId: 'cli-104',
    clientName: 'Élise Beauchamp',
    clientEmail: 'elise.beauchamp@outlook.com',
    clientPhone: '(450) 449-3310',
    address: '210 Rue De Montbrun',
    sector: 'Boucherville',
    issueDate: '2026-08-31',
    dueDate: '2026-09-14',
    items: [
      {
        id: 'item-1',
        serviceType: 'lawn_mowing',
        description: 'Forfait mensuel de tonte de pelouse - Août 2026 (4 passages)',
        quantity: 4,
        unit: 'visite',
        unitPrice: 55.0,
        total: 220.0,
      },
    ],
    subtotal: 220.0,
    tps: 11.0,
    tvq: 21.95,
    total: 252.95,
    applyTaxes: true,
    status: 'sent',
    notes: 'Veuillez effectuer le paiement par virement Interac à paiement@jardinducoin.ca',
    createdAt: '2026-08-31T17:05:00Z',
  },
  {
    id: 'inv-803',
    invoiceNumber: 'FAC-2026-144',
    clientId: 'cli-105',
    clientName: 'Guillaume & Karine Roy',
    clientEmail: 'roy.guillaume@sympatico.ca',
    clientPhone: '(514) 991-7782',
    address: '88 Avenue Elm',
    sector: 'Saint-Lambert',
    issueDate: '2026-08-15',
    dueDate: '2026-08-29',
    items: [
      {
        id: 'item-1',
        serviceType: 'mulch_soil',
        description: 'Livraison et installation de 4 verges de paillis noir de cèdre + désherbage des plates-bandes',
        quantity: 1,
        unit: 'forfait',
        unitPrice: 580.0,
        total: 580.0,
      },
    ],
    subtotal: 580.0,
    tps: 29.0,
    tvq: 57.86,
    total: 666.86,
    applyTaxes: true,
    status: 'overdue',
    notes: 'Rappel de paiement envoyé le 5 septembre.',
    createdAt: '2026-08-15T18:00:00Z',
  },
];
